import { Router } from 'express';
import store from '../../config/mockStore.js';
import { authenticate, authorize } from '../../middleware/auth.js';

const router = Router();

// Helper: convert array of objects to CSV string
function toCSV(data) {
    if (!data || data.length === 0) return '';
    const headers = Object.keys(data[0]).join(',');
    const rows = data.map(row =>
        Object.values(row).map(v => `"${String(v).replace(/"/g, '""')}"`).join(',')
    ).join('\n');
    return headers + '\n' + rows;
}

// Helper: generate HTML for PDF rendering via Puppeteer
function generateReportHTML(title, data, columns) {
    const rows = Array.isArray(data) ? data : (data.recent_events || data.slos || data.alerts || []);
    const cols = columns || (rows.length > 0 ? Object.keys(rows[0]) : []);

    return `<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>${title}</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #1a1a1a; }
  h1 { font-size: 22px; border-bottom: 2px solid #d4a017; padding-bottom: 8px; margin-bottom: 24px; }
  .meta { font-size: 12px; color: #666; margin-bottom: 20px; }
  table { width: 100%; border-collapse: collapse; font-size: 11px; }
  th { background: #f8f4e8; padding: 8px 6px; text-align: left; border-bottom: 2px solid #d4a017; font-weight: 600; text-transform: uppercase; font-size: 10px; letter-spacing: 0.5px; }
  td { padding: 6px; border-bottom: 1px solid #eee; }
  tr:nth-child(even) { background: #faf8f2; }
  .summary { display: flex; gap: 24px; margin-bottom: 24px; }
  .summary-card { padding: 12px 20px; background: #f8f4e8; border-radius: 6px; border-left: 3px solid #d4a017; }
  .summary-card .label { font-size: 10px; color: #888; text-transform: uppercase; }
  .summary-card .value { font-size: 20px; font-weight: bold; color: #1a1a1a; }
  .footer { margin-top: 30px; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
</style>
</head><body>
<h1>${title}</h1>
<div class="meta">Generated: ${new Date().toISOString()} | AI Observability Platform — Confidential</div>
${typeof data === 'object' && !Array.isArray(data) ? `
<div class="summary">
  ${Object.entries(data).filter(([k, v]) => typeof v !== 'object').map(([k, v]) =>
        `<div class="summary-card"><div class="label">${k.replace(/_/g, ' ')}</div><div class="value">${v}</div></div>`
    ).join('')}
</div>` : ''}
<table>
<thead><tr>${cols.map(c => `<th>${c.replace(/_/g, ' ')}</th>`).join('')}</tr></thead>
<tbody>${rows.map(row => `<tr>${cols.map(c => `<td>${row[c] !== undefined ? row[c] : ''}</td>`).join('')}</tr>`).join('')}</tbody>
</table>
<div class="footer">This report is auto-generated by the AI Observability Platform. All exports are logged in the audit trail.</div>
</body></html>`;
}

// Puppeteer PDF generation (lazy-loaded)
async function generatePDF(html) {
    const puppeteer = await import('puppeteer');
    const browser = await puppeteer.default.launch({
        headless: 'new',
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    const pdf = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' },
    });
    await browser.close();
    return pdf;
}

// Log export action
function logExport(req, reportType, format) {
    store.addAuditLog({
        action: 'REPORT_GENERATED',
        details: `${reportType} report exported as ${format}`,
        userId: req.user.id,
        userName: req.user.email,
        userRole: req.user.role,
        ipAddress: req.ip,
    });
}

// GET /api/reports/model-inventory
router.get('/model-inventory', authenticate, authorize('admin', 'analyst'), async (req, res, next) => {
    try {
        const { format, risk_tier, deployment_env } = req.query;
        const data = store.generateModelInventoryReport({ risk_tier, deployment_env });

        logExport(req, 'Model Inventory', format || 'json');

        if (format === 'csv') {
            res.setHeader('Content-Type', 'text/csv');
            res.setHeader('Content-Disposition', 'attachment; filename=model_inventory_report.csv');
            return res.send(toCSV(data));
        }
        if (format === 'pdf') {
            const html = generateReportHTML('Model Inventory Report', data);
            const pdf = await generatePDF(html);
            res.setHeader('Content-Type', 'application/pdf');
            res.setHeader('Content-Disposition', 'attachment; filename=model_inventory_report.pdf');
            return res.send(pdf);
        }
        res.json({ report: 'Model Inventory', generated_at: new Date().toISOString(), data });
    } catch (err) {
        next(err);
    }
});

// GET /api/reports/alert-incident-summary
router.get('/alert-incident-summary', authenticate, authorize('admin', 'analyst'), async (req, res, next) => {
    try {
        const { format, startDate, endDate } = req.query;
        const data = store.generateAlertIncidentSummary({ startDate, endDate });

        logExport(req, 'Alert & Incident Summary', format || 'json');

        if (format === 'csv') {
            res.setHeader('Content-Type', 'text/csv');
            res.setHeader('Content-Disposition', 'attachment; filename=alert_incident_summary.csv');
            return res.send(toCSV(data.alerts));
        }
        if (format === 'pdf') {
            const html = generateReportHTML('Alert & Incident Summary Report', data, null);
            const pdf = await generatePDF(html);
            res.setHeader('Content-Type', 'application/pdf');
            res.setHeader('Content-Disposition', 'attachment; filename=alert_incident_summary.pdf');
            return res.send(pdf);
        }
        res.json({ report: 'Alert & Incident Summary', generated_at: new Date().toISOString(), ...data });
    } catch (err) {
        next(err);
    }
});

// GET /api/reports/sla-breach
router.get('/sla-breach', authenticate, authorize('admin', 'analyst'), async (req, res, next) => {
    try {
        const { format } = req.query;
        const data = store.generateSLABreachReport();

        logExport(req, 'SLA Breach', format || 'json');

        if (format === 'csv') {
            res.setHeader('Content-Type', 'text/csv');
            res.setHeader('Content-Disposition', 'attachment; filename=sla_breach_report.csv');
            return res.send(toCSV(data.slos));
        }
        if (format === 'pdf') {
            const html = generateReportHTML('SLA Breach Report', data);
            const pdf = await generatePDF(html);
            res.setHeader('Content-Type', 'application/pdf');
            res.setHeader('Content-Disposition', 'attachment; filename=sla_breach_report.pdf');
            return res.send(pdf);
        }
        res.json({ report: 'SLA Breach', generated_at: new Date().toISOString(), ...data });
    } catch (err) {
        next(err);
    }
});

// GET /api/reports/governance-activity
router.get('/governance-activity', authenticate, authorize('admin', 'analyst'), async (req, res, next) => {
    try {
        const { format, startDate, endDate } = req.query;
        const data = store.generateGovernanceReport({ startDate, endDate });

        logExport(req, 'Governance Activity', format || 'json');

        if (format === 'csv') {
            res.setHeader('Content-Type', 'text/csv');
            res.setHeader('Content-Disposition', 'attachment; filename=governance_activity_report.csv');
            return res.send(toCSV(data.recent_events));
        }
        if (format === 'pdf') {
            const html = generateReportHTML('Governance Activity Report', data);
            const pdf = await generatePDF(html);
            res.setHeader('Content-Type', 'application/pdf');
            res.setHeader('Content-Disposition', 'attachment; filename=governance_activity_report.pdf');
            return res.send(pdf);
        }
        res.json({ report: 'Governance Activity', generated_at: new Date().toISOString(), ...data });
    } catch (err) {
        next(err);
    }
});

export default router;
